runtime: nodejs12


handlers:
- url: /(.*\.(css|js|gif|png|jpg|jpeg))$
  static_files: dist/curso-pwa-angular/\1
  upload: dist/curso-pwa-angular/(.*)

- url: /(.*)
  static_files: dist/curso-pwa-angular/index.html
  upload: dist/curso-pwa-angular/index.html
